version: '2'
services:
  microservice-jenius-bot:
    build:
      context: .
      args:
        - SERVICE_NAME=microservice-jenius-bot
        - NPM_REGISTRY
        - NPM_TOKEN
        - HTTP_PROXY
        - HTTPS_PROXY
    environment:
      - SERVICE_PORT=3000
      - WAIT_START=1
    ports:
      - 3000:3000
